Repository SukheeChoi/springframework-mini-project, pull requests merged in 2022-05, with the labels that each got.

#133 예약 탭 클릭후의 기능 구현.
  src/main/java/com/mycompany/webapp/controller/MyPageController.java
  src/main/java/com/mycompany/webapp/controller/ReservationController.java
  src/main/java/com/mycompany/webapp/dao/mybatis/DentistDao.java
  src/main/java/com/mycompany/webapp/service/DentistService.java
  src/main/resources/mybatis/mapper/dentist.xml
  src/main/resources/mybatis/mapper/point.xml
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
  src/main/webapp/WEB-INF/views/reservation/afterReservationUsingCalendar.jsp
  src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp
  src/main/webapp/WEB-INF/views/reservation/main.jsp
  src/main/webapp/WEB-INF/views/reservation/reservationUsingMap.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/css/reservation.css
Labels: PR completed

#137 예약을 위 치과 정보 상세 페이지구현(영업시간 표시 제외.)
  src/main/java/com/mycompany/webapp/controller/ReservationController.java
  src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp
  src/main/webapp/WEB-INF/views/reservation/main.jsp
Labels: PR completed

#138 예약을 위한 치과 정보 상세 페이지에서 영업시간 정보를 치과 서버로부터 받아와서 시간형식으로 표시하는 것 구현.
  src/main/java/com/mycompany/webapp/controller/ReservationController.java
  src/main/java/com/mycompany/webapp/dao/mybatis/MyDentistDao.java
  src/main/java/com/mycompany/webapp/service/MyDentistService.java
  src/main/resources/mybatis/mapper/myDentist.xml
  src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp
  src/main/webapp/WEB-INF/views/reservation/main.jsp
Labels: PR completed

#142 merger 매우 힘들다 commit...
  src/main/webapp/WEB-INF/views/treatment/main.jsp
Labels: PR completed

#154 #153 feat: 치료내역 모아보기 목록에서 하나 클릭시 넘어가는 기능 구현
  src/main/java/com/mycompany/webapp/controller/TreatmentController.java
  src/main/java/com/mycompany/webapp/dto/Treatment.java
  src/main/webapp/WEB-INF/views/home/login.jsp
  src/main/webapp/WEB-INF/views/treatment/details.jsp
  src/main/webapp/WEB-INF/views/treatment/imageShow.jsp
  src/main/webapp/WEB-INF/views/treatment/main.jsp
Labels: feature

#159 Sukhee myreservation
  src/main/webapp/WEB-INF/views/myPage/myReservationList.jsp
Labels: PR completed

#162 Sukhee myreservation
  src/main/java/com/mycompany/webapp/controller/ReservationController.java
  src/main/webapp/WEB-INF/views/reservation/afterReservationUsingCalendar.jsp
  src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp
  src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp
Labels: PR completed

#165 #124 feat: 치료내역 '후기 작성하기' 기능 구현
  src/main/java/com/mycompany/webapp/controller/DentistController.java
  src/main/java/com/mycompany/webapp/controller/TreatmentController.java
  src/main/java/com/mycompany/webapp/dao/mybatis/DentistDao.java
  src/main/java/com/mycompany/webapp/service/DentistService.java
  src/main/resources/mybatis/mapper/dentist.xml
  src/main/webapp/WEB-INF/views/reservation/dentistDetail.jsp
  src/main/webapp/WEB-INF/views/treatment/details.jsp
  src/main/webapp/WEB-INF/views/treatment/main.jsp
  src/main/webapp/WEB-INF/views/treatment/reviewForm.jsp
  src/main/webapp/resources/css/app.css
Labels: feature

#167 Sukhee myreservation
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
Labels: PR completed

#181 #127 feat: 레이아웃 개선(myPage/main, myInformation, myDentist)
  src/main/webapp/WEB-INF/views/myPage/main.jsp
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
  src/main/webapp/WEB-INF/views/myPage/myInformation.jsp
  src/main/webapp/WEB-INF/views/treatment/details.jsp
  src/main/webapp/WEB-INF/views/treatment/main.jsp
  src/main/webapp/resources/css/app.css
  src/main/webapp/resources/css/common/empty-block.css
  src/main/webapp/resources/css/common/header.css
  src/main/webapp/resources/css/common/pagination.css
  src/main/webapp/resources/css/myPage/main.css
  src/main/webapp/resources/css/myPage/myDentist.css
  src/main/webapp/resources/css/myPage/myInformation.css
  src/main/webapp/resources/css/treatment/treatment.css
Labels: feature, layout

#183 #182 debug: loading.jsp 내용수정 및 위치 일부 수정(나머지는 동현쓰에게 토스)
  src/main/webapp/WEB-INF/views/common/loading.jsp
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
Labels: bug

#196 #186 feat: 예약현황 화면에서 예약취소 선택 시 confirm 모달 구현
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
  src/main/webapp/WEB-INF/views/myPage/myReservationList.jsp
Labels: feature

#203 #201 feat: myDentist.jsp페이지 denno->dendomain으로 변경
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
  src/main/webapp/resources/css/reservation/reservationUsingMap.css
Labels: feature

#212 #211 feat && refactor: 검색바 UI컴포넌트 추가 및 기존 컴포넌트 수정
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
  src/main/webapp/resources/css/common/empty-block.css
  src/main/webapp/resources/css/common/list-item.css
  src/main/webapp/resources/css/common/search-bar.css
  src/main/webapp/resources/css/myPage/myDentist.css
Labels: layout, refactor

#213 #199 feat: 진료예약 main화면 기능구현 및 레이아웃 개선
  src/main/java/com/mycompany/webapp/controller/MyPageController.java
  src/main/java/com/mycompany/webapp/controller/ReservationController.java
  src/main/resources/mybatis/mapper/dentist.xml
  src/main/webapp/WEB-INF/views/reservation/main.jsp
  src/main/webapp/WEB-INF/views/reservation/reservationUsingMap.jsp
  src/main/webapp/resources/css/common/list-item.css
  src/main/webapp/resources/css/reservation.css
  src/main/webapp/resources/css/reservation/main.css
  src/main/webapp/resources/images/no-image.jpg
Labels: bug, feature, layout, refactor

#217 #216 debug: 치료내역상세 > 리뷰작성화면에서 치료내역의 요약정보가 뜨지 않던 현상 해결
  src/main/webapp/WEB-INF/views/treatment/reviewForm.jsp
Labels: bug

#219 #127 feat: 치과상세페이지(지도) 화면 시안과 비슷하게 작업
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/myPage/main.jsp
  src/main/webapp/WEB-INF/views/reservation/reservationUsingMap.jsp
  src/main/webapp/resources/css/common/header.css
  src/main/webapp/resources/css/myPage/main.css
  src/main/webapp/resources/css/reservation/reservationUsingMap.css
  src/main/webapp/resources/images/logo-spring.png
  src/main/webapp/resources/images/map.png
  src/main/webapp/resources/images/myDentistList.jpg
  src/main/webapp/resources/images/signOut.jpg
  src/main/webapp/resources/images/ㅠㅠ.png
Labels: feature, layout

#222 #127 feat: 레이아웃 개선(진료예약 달력 화면)
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/reservation/reservationUsingCalendar.jsp
  src/main/webapp/resources/css/reservation/reservationUsingCalendar.css
Labels: feature, layout

#225 #223 feat: 리스트아이템마다 썸네일 띄워주는 기능 구현(treatment 메인목록, 내치과 메인목록)
  src/main/webapp/WEB-INF/views/myPage/myDentist.jsp
  src/main/webapp/WEB-INF/views/treatment/details.jsp
  src/main/webapp/WEB-INF/views/treatment/main.jsp
  src/main/webapp/resources/css/myPage/myDentist.css
Labels: feature, layout

#226 #127 feat: 레이아웃 개선(내포인트 화면)
  src/main/webapp/WEB-INF/views/myPage/myPointList.jsp
Labels: feature, layout

#229 #228 feat: 메인화면 캐러셀 삭제하고 주기능설명 이미지 추가
  src/main/webapp/WEB-INF/views/home/main.jsp
  src/main/webapp/resources/css/home/home.css
  src/main/webapp/resources/images/intro/intro1_crop.png
  src/main/webapp/resources/images/intro/intro2.png
  src/main/webapp/resources/images/intro/intro3.png
Labels: layout
